server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: user-service

logging:
  level:
    org.exampledriven.eureka: DEBUG
    
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    format_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-test?autoReconnect=true&autoReconnectForPools=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: admin
    password: admin
  redis:
    hostName: 192.168.1.158
    port: 6379
    maxActive: 8
    maxWait: 1
    maxIdle: 8
    minIdle: 0
    timeout: 0